image: keymetrics/pm2:6
stages:
  - deploy
deploy_prod:
  stage: deploy
  script:
    - echo "make deploy"
    - cd pum/PUMApp
    - git pull
    - ng build --prod
    - rm /data/www/pumapp/*
    - cp -R dist/. /data/www/pumapp
  environment:
    name: deploying
  only:
  - dev
  
  
  
  